### ISSUE TITLE
[Bug report]in windows,build Gravitino pop error: Execution failed for task ':web:prettierCheck'

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#1207]
### Describe what's wrong

build Gravitino in windows failed.

### Error message and/or stacktrace

[warn] Code style issues found in 80 files. Run Prettier to fix.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Build gravitino FAILURE reason:
    Execution failed for task ':web:prettierCheck':
        org.gradle.process.internal.ExecException: Process 'command 'E:\datastrato\gravitino\web\.gradle\yarn\yarn-v1.22.19\yarn.cmd'' finished with non-zero exit value 1
            at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:415)
            at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:38)
            at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:202)
            at org.gradle.process.internal.DefaultExecOperations.exec(DefaultExecOperations.java:37)
            at com.github.gradle.node.util.DefaultProjectApiHelper.exec(ProjectApiHelper.kt:73)
            at com.github.gradle.node.exec.ExecRunner.execute(ExecRunner.kt:10)
            at com.github.gradle.node.yarn.exec.YarnExecRunner.executeYarnCommand(YarnExecRunner.kt:34)
            at com.github.gradle.node.yarn.task.YarnTask.exec(YarnTask.kt:74)
            at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
            at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:248)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)

### How to reproduce

1.windows system
2.run command: ./gradlew build -PskipITs -PskipTests

**Comment by FANNG1** [comment]
Gravitino only support build on mac or Linux, please refer to https://datastrato.ai/docs/0.3.0/how-to-build

**Comment by yuqi1129** [comment]
> Gravitino only support build on mac or Linux, please refer to [datastrato.ai/docs/0.3.0/how-to-build](https://datastrato.ai/docs/0.3.0/how-to-build)

Her work PC is running Windows OS, I think we should resolve it, at least make it built and run on the Windows platform.

**Comment by jerryshao** [comment]
Close this as we don't fully support Windows for now.
