### ISSUE TITLE
[Subtask] Check web e2e test in the Windows OS

### ISSUE THREAD

**Issue by xunliu** [apache/gravitino#1687]
### Describe the subtask

I tested the web e2e test in the macOS and Github Action Linux OS.
If you have time please help me test in the Windows OS, thanks.

Execute next command:
```
cd gravition
./gradlew clean build -x test
./gradlew :integration-test:test --tests "com.datastrato.gravitino.integration.test.web.ui.MetalakePageTest.homePage"
```

### Parent issue

#1503

**Comment by Xiao75896453** [comment]
To @xunliu 
Hi, I want to check that you mean windows OS is WSL or native windows OS (ex windows 11) ? thanks 🙏

**Comment by shaofengshi** [comment]
I'm on Windows 10 platform; I can run the test if needed.

**Comment by evalaiyc98** [comment]
Thanks for offering to test on Windows 10! @shaofengshi
And actually, I have tested this on WSL 2 on Windows 11, but I'm not sure if this is the main purpose of the issue.

And following is the screenshot of the web e2e test on WSL:

![web-e2e-WSL](https://github.com/datastrato/gravitino/assets/139951533/f49273ef-4528-485a-b936-a5adfa6cf16e)

**Comment by shaofengshi** [comment]
I'm on Windows 10, with openjdk version "1.8.0_392" and Gradle 8.5; I run "./gradlew clean build -x test" got the following result:

[warn] types/global.d.ts
[warn] Code style issues found in 92 files. Run Prettier to fix.
 ELIFECYCLE▒? Command failed with exit code 1.

> Task :web:prettierCheck FAILED

Build gravitino FAILURE reason:
    Execution failed for task ':web:prettierCheck':
        org.gradle.process.internal.ExecException: Process 'command 'C:\Users\pan\workspace\gravitino\web\.gradle\pnpm\pnpm-latest\pnpm.cmd'' finished with non-zero exit value 1
            at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:415)
            at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:38)
            at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:202)
            at org.gradle.process.internal.DefaultExecOperations.exec(DefaultExecOperations.java:37)
            at com.github.gradle.node.util.DefaultProjectApiHelper.exec(ProjectApiHelper.kt:68)
            at com.github.gradle.node.exec.ExecRunner.execute(ExecRunner.kt:46)
            at com.github.gradle.node.pnpm.exec.PnpmExecRunner.executeCommand(PnpmExecRunner.kt:38)
            at com.github.gradle.node.pnpm.exec.PnpmExecRunner.executePnpmCommand(PnpmExecRunner.kt:26)
            at com.github.gradle.node.pnpm.task.PnpmTask.exec(PnpmTask.kt:76)
            at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
            at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:248)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
            at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:233)
            at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:216)
            at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:199)
            at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:166)
            at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
            at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
            at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
            at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
            at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
            at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
            at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
            at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
            at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
            at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
            at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
            at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
            at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:28)
            at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:100)
            at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:72)
            at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:50)
            at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
            at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
            at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:179)
            at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:70)
            at org.gradle.internal.Either$Right.fold(Either.java:175)
            at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
            at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:68)
            at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:46)
            at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
            at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
            at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
            at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
            at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:91)
            at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:55)
            at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
            at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:37)
            at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65)
            at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36)
            at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
            at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
            at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:77)
            at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:38)
            at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:94)
            at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:49)
            at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:71)
            at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:45)
            at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNonEmptySources(SkipEmptyWorkStep.java:177)
            at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:81)
            at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:53)
            at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
            at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
            at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
            at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
            at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
            at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:75)
            at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:41)
            at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:32)
            at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:293)
            at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
            at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:21)
            at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
            at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
            at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:47)
            at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:34)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':web:prettierCheck'.
> Process 'command 'C:\Users\pan\workspace\gravitino\web\.gradle\pnpm\pnpm-latest\pnpm.cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 7m 7s
164 actionable tasks: 155 executed, 3 from cache, 6 up-to-date

**Comment by xunliu** [comment]
@ch3yne Please check here for `web` module compile problems.

> I'm on Windows 10, with openjdk version "1.8.0_392" and Gradle 8.5; I run "./gradlew clean build -x test" got the following result:
> 
> [warn] types/global.d.ts [warn] Code style issues found in 92 files. Run Prettier to fix.  ELIFECYCLE▒? Command failed with exit code 1.
> 
> > Task :web:prettierCheck FAILED
> 
> Build gravitino FAILURE reason: Execution failed for task ':web:prettierCheck': org.gradle.process.internal.ExecException: Process 'command 'C:\Users\pan\workspace\gravitino\web.gradle\pnpm\pnpm-latest\pnpm.cmd'' finished with non-zero exit value 1 at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:415) at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:38) at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:202) at org.gradle.process.internal.DefaultExecOperations.exec(DefaultExecOperations.java:37) at com.github.gradle.node.util.DefaultProjectApiHelper.exec(ProjectApiHelper.kt:68) at com.github.gradle.node.exec.ExecRunner.execute(ExecRunner.kt:46) at com.github.gradle.node.pnpm.exec.PnpmExecRunner.executeCommand(PnpmExecRunner.kt:38) at com.github.gradle.node.pnpm.exec.PnpmExecRunner.executePnpmCommand(PnpmExecRunner.kt:26) at com.github.gradle.node.pnpm.task.PnpmTask.exec(PnpmTask.kt:76) at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125) at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58) at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51) at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29) at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:248) at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29) at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26) at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66) at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59) at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157) at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59) at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47) at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68) at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:233) at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:216) at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:199) at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:166) at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105) at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44) at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59) at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56) at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204) at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199) at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66) at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59) at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157) at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59) at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53) at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73) at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56) at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44) at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67) at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37) at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41) at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74) at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55) at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50) at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:28) at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:100) at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:72) at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:50) at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40) at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29) at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:179) at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:70) at org.gradle.internal.Either$Right.fold(Either.java:175) at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59) at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:68) at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:46) at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36) at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25) at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36) at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22) at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:91) at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:55) at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55) at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:37) at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65) at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36) at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37) at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27) at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:77) at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:38) at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:94) at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:49) at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:71) at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:45) at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNonEmptySources(SkipEmptyWorkStep.java:177) at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:81) at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:53) at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32) at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21) at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38) at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36) at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23) at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:75) at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:41) at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:32) at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:293) at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30) at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:21) at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37) at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27) at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:47) at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:34)
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':web:prettierCheck'.
> 
> > Process 'command 'C:\Users\pan\workspace\gravitino\web.gradle\pnpm\pnpm-latest\pnpm.cmd'' finished with non-zero exit value 1
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
> 
> BUILD FAILED in 7m 7s 164 actionable tasks: 155 executed, 3 from cache, 6 up-to-date

**Comment by ch3yne** [comment]
> I'm on Windows 10, with openjdk version "1.8.0_392" and Gradle 8.5; I run "./gradlew clean build -x test" got the following result:
> 
> [warn] types/global.d.ts
> [warn] Code style issues found in 92 files. Run Prettier to fix.  ELIFECYCLE▒? Command failed with exit code 1.

@shaofengshi It seems that used the different end-of-line. If you installed the Nodejs environment, running `pnpm format`.

**Comment by justinmclean** [comment]
You can also set up Git to convert newlines see https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#

**Comment by shaofengshi** [comment]
> > I'm on Windows 10, with openjdk version "1.8.0_392" and Gradle 8.5; I run "./gradlew clean build -x test" got the following result:
> > [warn] types/global.d.ts
> > [warn] Code style issues found in 92 files. Run Prettier to fix.  ELIFECYCLE▒? Command failed with exit code 1.
> 
> @shaofengshi It seems that used the different end-of-line. If you installed the Nodejs environment, running `pnpm format` before.

after executing '.\web\.gradle\pnpm\pnpm-latest\pnpm.cmd format' under the web module, the "gradle clean build -x test" got success on Windows:

![1706716685673](https://github.com/datastrato/gravitino/assets/5411805/8d78d782-19ce-4fd4-aa65-3d925605702a)

**Comment by shaofengshi** [comment]
The integration test on Windows couldn't succeed due to several reasons:

1) Got the following wrong classpath error. After doing some debug, I know that Backslashes ("\") are for escaped character in Windows; That means, the gravitino.auxService.iceberg-rest.classpath "catalogs\catalog-lakehouse-iceberg\build\libs" will be parsed as "catalogscatalog-lakehouse-icebergbuildlibs", which couldn't be recognized correctly, see https://stackoverflow.com/questions/11494177/javas-file-tostring-or-path-tostring-with-a-specific-path-separator . To bypass it, need to fix in MiniGravitino.java line 190 to 193, add "replace('\\', '/')" for the two variables. 
java.lang.IllegalArgumentException: AuxService:iceberg-rest, classpath: catalogscatalog-lakehouse-icebergbuildlibs not exists, gravitinoHome:C:\Users\pan\workspace\gravitino
                    at com.datastrato.gravitino.auxiliary.AuxiliaryServiceManager.getValidPath(AuxiliaryServiceManager.java:102)
![6226414a39de9986bc6f5fb21453a15](https://github.com/datastrato/gravitino/assets/5411805/3c356c7b-3813-43b4-b7a8-9323ed143d59)

2) After solving the first issue, I encountered the second quickly, which is related to the "pgrep" command. It seems that this command has different options on Mac and Windows. The scripts in "integration-test/build.gradle.kts" is written and tested on Mac OS, not for Windows. 

> Task :integration-test:test
pgrep: invalid option -- 'q'

Usage:
 pgrep [options] <pattern>

For more details see pgrep(1).
checkContainerRunning command execution failed: Process 'command 'bash'' finished with non-zero exit value 2
Current docker context is: default

MetalakePageTest > initializationError FAILED
    java.lang.RuntimeException: Webpage not loaded in 60 seconds.
        at com.datastrato.gravitino.integration.test.web.ui.utils.WebDriverManager.getWebDriver(WebDriverManager.java:53)

1 test completed, 1 failed

> Task :integration-test:test FAILED

FAILURE: Build failed with an exception.


In a short, the e2e test doesn't support Windows at this moment. That's what I collected so far.
