### ISSUE TITLE
[Bug report] frondend integrate test may failed

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#3786]
### Version

main branch

### Describe what's wrong

 frondend integrate test may failed

### Error message and/or stacktrace

https://github.com/datastrato/gravitino/actions/runs/9380298328/job/25827057838?pr=3703
```
CatalogsPageTest > testClickCatalogLink() FAILED
    org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
        at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
        at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)
        at com.datastrato.gravitino.integration.test.web.ui.CatalogsPageTest.testClickCatalogLink(CatalogsPageTest.java:396)
```

### How to reproduce

ci

**Comment by zivali** [comment]
It seems https://github.com/apache/gravitino/pull/3965 fixed this issue.

**Comment by FANNG1** [comment]
thanks @zivali for reminding, close it
