### ISSUE TITLE
[Bug report] CI: occasionally run trino tpcds testsets failed because clean up test env unsuccessfully

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#3792]
### Version

main branch

### Describe what's wrong

```
+ ./gradlew :integration-test:TrinoTest '-PappArgs="--auto=none --test_set=tpcds --postgresql_uri=jdbc:postgresql://pg-16-postgresql.relational-catalog:5432 --mysql_uri=jdbc:mysql://my-8-mysql.relational-catalog:3306 --hdfs_uri=hdfs://hadoop-hdfs-namenode.hadoop:8020 --hive_uri=thrift://hadoop-metastore.hadoop:9083 --gravitino_uri=http://a6a4dafea8d0e42bb92a3a0cc2668290-130770707.ap-northeast-1.elb.amazonaws.com:8090 --trino_uri=http://a58a73d540fee4bb887b6d8d61e5ab33-1505358297.ap-northeast-1.elb.amazonaws.com:8080"'

> Configure project :
checkContainerRunning command execution failed: Process 'command 'bash'' finished with non-zero exit value 1
Current docker context is: desktop-linux

------------------ Check Docker environment ---------------------
Docker server status ............................................ [running]
mac-docker-connector status ..................................... [stop]
OrbStack status ................................................. [no]
Run test cases without `gravitino-docker-it` tag ................ [embedded test]
-----------------------------------------------------------------
Tip: Please make sure to use OrbStack or execute the `dev/docker/tools/mac-docker-connector.sh` script before running the integration test on macOS.

> Configure project :web
Kotlin DSL property assignment is an incubating feature.

> Task :common:jar
WARN: Unable to get Git commit id : /Users/wangdanhua/Workspace/test/gravitino-main/.git/HEAD (No such file or directory)

> Task :integration-test:TrinoTest
6月 05, 2024 8:20:38 下午 org.jline.utils.Log logr
警告: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
2024-06-05 20:20:40 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_hive2".gt_tpch.customer
2024-06-05 20:20:40 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_hive2".gt_tpch.lineitem
2024-06-05 20:20:41 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_hive2".gt_tpch.nation
2024-06-05 20:20:41 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_hive2".gt_tpch.orders
2024-06-05 20:20:41 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_hive2".gt_tpch.part
2024-06-05 20:20:42 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_hive2".gt_tpch.partsupp
2024-06-05 20:20:42 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_hive2".gt_tpch.region
....
2024-06-05 20:20:49 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_mysql2".gt_tpch.customer
2024-06-05 20:20:49 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_mysql2".gt_tpch.lineitem
2024-06-05 20:20:49 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_mysql2".gt_tpch.nation
2024-06-05 20:20:49 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_mysql2".gt_tpch.orders
2024-06-05 20:20:49 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_mysql2".gt_tpch.part
2024-06-05 20:20:50 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_mysql2".gt_tpch.partsupp
2024-06-05 20:20:50 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_mysql2".gt_tpch.region
2024-06-05 20:20:50 INFO  [main] TrinoQueryITBase:202 - Drop table "test.gt_mysql2".gt_tpch.supplier
2024-06-05 20:20:50 INFO  [main] TrinoQueryITBase:217 - Drop schema "test.gt_mysql2".gt_tpch
2024-06-05 20:20:50 INFO  [main] TrinoQueryITBase:221 - Drop catalog "test.gt_mysql2"
Failed to clean up test env: Failed to operate object [gt_iceberg2] operation [DROP] under [test], reason [Entity test.gt_iceberg2 has sub-entities [test.gt_iceberg2.gt_tpch2], you should remove sub-entities first]
com.datastrato.gravitino.exceptions.NonEmptyEntityException: Entity test.gt_iceberg2 has sub-entities [test.gt_iceberg2.gt_tpch2], you should remove sub-entities first
        at com.datastrato.gravitino.storage.kv.KvEntityStore.lambda$delete$5(KvEntityStore.java:280)
        at com.datastrato.gravitino.storage.FunctionUtils.executeInTransaction(FunctionUtils.java:58)
        at com.datastrato.gravitino.storage.kv.KvEntityStore.executeInTransaction(KvEntityStore.java:300)
        at com.datastrato.gravitino.storage.kv.KvEntityStore.delete(KvEntityStore.java:248)
        at com.datastrato.gravitino.EntityStore.delete(EntityStore.java:145)
        at com.datastrato.gravitino.catalog.CatalogManager.dropCatalog(CatalogManager.java:518)
        at com.datastrato.gravitino.catalog.CatalogNormalizeDispatcher.dropCatalog(CatalogNormalizeDispatcher.java:90)
        at com.datastrato.gravitino.listener.CatalogEventDispatcher.dropCatalog(CatalogEventDispatcher.java:137)
        at com.datastrato.gravitino.server.web.rest.CatalogOperations.lambda$dropCatalog$8(CatalogOperations.java:200)
        at com.datastrato.gravitino.lock.TreeLockUtils.doWithTreeLock(TreeLockUtils.java:35)
        at com.datastrato.gravitino.server.web.rest.CatalogOperations.lambda$dropCatalog$9(CatalogOperations.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at com.datastrato.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:25)


```

### Error message and/or stacktrace

```
Caused by: java.lang.RuntimeException: Failed to operate object [gt_iceberg2] operation [DROP] under [test], reason [Entity test.gt_iceberg2 has sub-entities [test.gt_iceberg2.gt_tpch2], you should remove sub-entities first]
com.datastrato.gravitino.exceptions.NonEmptyEntityException: Entity test.gt_iceberg2 has sub-entities [test.gt_iceberg2.gt_tpch2], you should remove sub-entities first
        at com.datastrato.gravitino.storage.kv.KvEntityStore.lambda$delete$5(KvEntityStore.java:280)
        at com.datastrato.gravitino.storage.FunctionUtils.executeInTransaction(FunctionUtils.java:58)
        at com.datastrato.gravitino.storage.kv.KvEntityStore.executeInTransaction(KvEntityStore.java:300)
        at com.datastrato.gravitino.storage.kv.KvEntityStore.delete(KvEntityStore.java:248)
        at com.datastrato.gravitino.EntityStore.delete(EntityStore.java:145)
        at com.datastrato.gravitino.catalog.CatalogManager.dropCatalog(CatalogManager.java:518)
        at com.datastrato.gravitino.catalog.CatalogNormalizeDispatcher.dropCatalog(CatalogNormalizeDispatcher.java:90)
        at com.datastrato.gravitino.listener.CatalogEventDispatcher.dropCatalog(CatalogEventDispatcher.java:137)
        at com.datastrato.gravitino.server.web.rest.CatalogOperations.lambda$dropCatalog$8(CatalogOperations.java:200)
        at com.datastrato.gravitino.lock.TreeLockUtils.doWithTreeLock(TreeLockUtils.java:35)
        at com.datastrato.gravitino.server.web.rest.CatalogOperations.lambda$dropCatalog$9(CatalogOperations.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at com.datastrato.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:25)
        at com.datastrato.gravitino.server.web.Utils.doAs(Utils.java:121)
        at com.datastrato.gravitino.server.web.rest.CatalogOperations.dropCatalog(CatalogOperations.java:192)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)

```

### How to reproduce

1.Run tpch testsets
```
 ./gradlew :integration-test:TrinoTest '-PappArgs="--auto=none --test_set=tpch --postgresql_uri=jdbc:postgresql://pg-16-postgresql.relational-catalog:5432 --mysql_uri=jdbc:mysql://my-8-mysql.relational-catalog:3306 --hdfs_uri=hdfs://hadoop-hdfs-namenode.hadoop:8020 --hive_uri=thrift://hadoop-metastore.hadoop:9083 --gravitino_uri=http://a6a4dafea8d0e42bb92a3a0cc2668290-130770707.ap-northeast-1.elb.amazonaws.com:8090 --trino_uri=http://a58a73d540fee4bb887b6d8d61e5ab33-1505358297.ap-northeast-1.elb.amazonaws.com:8080"'
```
2.Run tpcds testsets
```
 ./gradlew :integration-test:TrinoTest '-PappArgs="--auto=none --test_set=tpcds --postgresql_uri=jdbc:postgresql://pg-16-postgresql.relational-catalog:5432 --mysql_uri=jdbc:mysql://my-8-mysql.relational-catalog:3306 --hdfs_uri=hdfs://hadoop-hdfs-namenode.hadoop:8020 --hive_uri=thrift://hadoop-metastore.hadoop:9083 --gravitino_uri=http://a6a4dafea8d0e42bb92a3a0cc2668290-130770707.ap-northeast-1.elb.amazonaws.com:8090 --trino_uri=http://a58a73d540fee4bb887b6d8d61e5ab33-1505358297.ap-northeast-1.elb.amazonaws.com:8080"'
```

**Comment by jerryshao** [comment]
@diqiu50 please take a look.

**Comment by diqiu50** [comment]
@danhuawang If the last round of testing failed, you'd better clear all the test resources manually. The Drop Catalog interface on the Gravitino server has some limitations for non-empty catalogs.

**Comment by danhuawang** [comment]
> @danhuawang If the last round of testing failed, you'd better clear all the test resources manually. The Drop Catalog interface on the Gravitino server has some limitations for non-empty catalogs.

@diqiu50 You mean we don't support drop non-empty catalogs , right?

**Comment by diqiu50** [comment]
Yes

**Comment by danhuawang** [comment]
> Yes

It means Trino sql test don't support rerun on the same environment, and should run on a clean environment.                           I closed this issue since there is no plan to support rerun all sql tests on the same environment.
