### ISSUE TITLE
[Bug report] create schema/table with the upper case name in postgresql database, response 404

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#3817]
### Version

main branch

### Describe what's wrong

<img width="1470" alt="image" src="https://github.com/datastrato/gravitino/assets/154112360/d53d27c9-b3e4-4d2a-a52d-b05155ecd6b5">

### Error message and/or stacktrace

2024-06-07 15:49:51.713 INFO [Gravitino-webserver-53] [com.datastrato.gravitino.server.web.rest.TableOperations.lambda$listTables$1(TableOperations.java:78)] - List 0 tables under schema: i.p.upper
2024-06-07 15:49:56.992 INFO [Gravitino-webserver-66] [com.datastrato.gravitino.server.web.rest.SchemaOperations.createSchema(SchemaOperations.java:93)] - Received create schema request: i.p.D
2024-06-07 15:49:56.994 INFO [Gravitino-webserver-66] [com.datastrato.gravitino.catalog.jdbc.operation.JdbcDatabaseOperations.create(JdbcDatabaseOperations.java:41)] - Beginning to create database D
2024-06-07 15:49:56.997 INFO [Gravitino-webserver-66] [com.datastrato.gravitino.catalog.jdbc.operation.JdbcDatabaseOperations.create(JdbcDatabaseOperations.java:45)] - Finished creating database D
2024-06-07 15:49:57.000 WARN [Gravitino-webserver-66] [com.datastrato.gravitino.server.web.rest.ExceptionHandlers$SchemaExceptionHandler.handle(ExceptionHandlers.java:177)] - Failed to operate schema(s) [D] operation [CREATE] under catalog [p], reason [No such schema: D]
com.datastrato.gravitino.exceptions.NoSuchSchemaException: No such schema: D
        at com.datastrato.gravitino.catalog.postgresql.operation.PostgreSqlSchemaOperations.load(PostgreSqlSchemaOperations.java:66) ~[?:?]
        at com.datastrato.gravitino.catalog.jdbc.JdbcCatalogOperations.loadSchema(JdbcCatalogOperations.java:208) ~[?:?]
        at com.datastrato.gravitino.catalog.jdbc.JdbcCatalogOperations.loadSchema(JdbcCatalogOperations.java:63) ~[?:?]
        at com.datastrato.gravitino.catalog.SchemaOperationDispatcher.lambda$createSchema$6(SchemaOperationDispatcher.java:119) ~[gravitino-core-0.5.1.jar:?]
        at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithSchemaOps$0(CatalogManager.java:103) ~[gravitino-core-0.5.1.jar:?]
        at com.datastrato.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:72) ~[gravitino-core-0.5.1.jar:?]
        at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.doWithSchemaOps(CatalogManager.java:98) ~[gravitino-core-0.5.1.jar:?]
        at com.datastrato.gravitino.catalog.SchemaOperationDispatcher.lambda$createSchema$7(SchemaOperationDispatcher.java:119) ~[gravitino-core-0.5.1.jar:?]
        at com.datastrato.gravitino.catalog.OperationDispatcher.doWithCatalog(OperationDispatcher.java:87) ~[gravitino-core-0.5.1.jar:?]
        at com.datastrato.gravitino.catalog.SchemaOperationDispatcher.createSchema(SchemaOperationDispatcher.java:117) ~[gravitino-core-0.5.1.jar:?]
        at com.datastrato.gravitino.catalog.SchemaNormalizeDispatcher.createSchema(SchemaNormalizeDispatcher.java:47) ~[gravitino-core-0.5.1.jar:?]
        at com.datastrato.gravitino.listener.SchemaEventDispatcher.createSchema(SchemaEventDispatcher.java:76) ~[gravitino-core-0.5.1.jar:?]
        at com.datastrato.gravitino.server.web.rest.SchemaOperations.lambda$createSchema$2(SchemaOperations.java:105) ~[gravitino-server-0.5.1.jar:?]
        at com.datastrato.gravitino.lock.TreeLockUtils.doWithTreeLock(TreeLockUtils.java:35) ~[gravitino-core-0.5.1.jar:?]
        at com.datastrato.gravitino.server.web.rest.SchemaOperations.lambda$createSchema$3(SchemaOperations.java:101) ~[gravitino-server-0.5.1.jar:?]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.base/javax.security.auth.Subject.doAs(Subject.java:439) ~[?:?]
        at com.datastrato.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:25) ~[gravitino-core-0.5.1.jar:?]
        at com.datastrato.gravitino.server.web.Utils.doAs(Utils.java:121) ~[gravitino-server-0.5.1.jar:?]
        at com.datastrato.gravitino.server.web.rest.SchemaOperations.createSchema(SchemaOperations.java:95) ~[gravitino-server-0.5.1.jar:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at com.datastrato.gravitino.server.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:59) ~[gravitino-server-common-0.5.1.jar:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at com.datastrato.gravitino.server.web.VersioningFilter.doFilter(VersioningFilter.java:97) ~[gravitino-server-0.5.1.jar:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]

### How to reproduce

1. start gravitino server
2. start a pg instance:
```
docker run -itd -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 --name postgresql16 postgres:16
```
3. create a schema named: "UPS" in the pg catalog

**Comment by mchades** [comment]
This is not caused by the normalization of Gravitino but by the PG catalog. Can you help confirm this? @yuqi1129

**Comment by danhuawang** [comment]
@yuqi1129   I can create schema with upper case, but I can't delete it.  I can delete pg schema if I create it by lower case

![Image](https://github.com/user-attachments/assets/494f9c53-ab68-46aa-b2b9-69886e6b45cb)



![Image](https://github.com/user-attachments/assets/b284fba1-08e7-49b0-9a7f-183e2edaba83)
