### ISSUE TITLE
[Bug report] Doris container startup fails during PR build in frontend IT

### ISSUE THREAD

**Issue by zivali** [apache/gravitino#3870]
### Version

main branch

### Describe what's wrong

Local build works fine. 
But during Github Actions, Frontend Integration Test continuously fails with `CatalogsPageDorisTest > initializationError FAILED`
Should we prolong the wait time in checkContainerStatus?
https://github.com/datastrato/gravitino/blob/main/integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/DorisContainer.java#L94-L103

### Error message and/or stacktrace

https://github.com/datastrato/gravitino/actions/runs/9535519315/job/26281349427?pr=2335
```
CatalogsPageDorisTest > initializationError FAILED
    org.testcontainers.shaded.org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in com.datastrato.gravitino.integration.test.container.DorisContainer that uses java.lang.String was not fulfilled within 30 seconds.
        at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
        at org.testcontainers.shaded.org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
        at org.testcontainers.shaded.org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
        at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
        at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
        at com.datastrato.gravitino.integration.test.container.DorisContainer.checkContainerStatus(DorisContainer.java:102)
        at com.datastrato.gravitino.integration.test.container.DorisContainer.start(DorisContainer.java:64)
        at com.datastrato.gravitino.integration.test.container.ContainerSuite.startDorisContainer(ContainerSuite.java:177)
        at com.datastrato.gravitino.integration.test.web.ui.CatalogsPageDorisTest.before(CatalogsPageDorisTest.java:70)

44 tests completed, 1 failed
```

### How to reproduce

Open a PR which might trigger Frontend Integration Test.

**Comment by bknbkn** [comment]
I also encountered the same problem. This may be due to the slow startup of the doris container. I slove it by increasing the max wait time from 30s to a suitable time.

**Comment by zhoukangcn** [comment]
@zivali I will check this failure. But I need to take a look at upload-artifact

<img width="677" alt="image" src="https://github.com/datastrato/gravitino/assets/6739160/465c0fab-c820-42b4-9a95-177918deb089">

**Comment by zhoukangcn** [comment]
> I also encountered the same problem. This may be due to the slow startup of the doris container. I slove it by increasing the max wait time from 30s to a suitable time.

@bknbkn Do you mean increase the max wait time in your local machine?

**Comment by bknbkn** [comment]
@zhoukangcn yes, I change MAX_WAIT from 30s to 180s and can pass test

**Comment by zhoukangcn** [comment]
@zivali @bknbkn  as #3883 has been merged. This PR will help Doris container startup more quickly.

I will keep my eyes on Frontend IT. If you find any new problems, please tell me.

**Comment by yuqi1129** [comment]
This has been resolved.
