### ISSUE TITLE
[Improvement] add error retry to TestFetchFileUtils

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#4483]
### What would you like to be improved?

TestFetchFileUtils maybe failed for network, we could add some retry by using `await`

```
TestFetchFileUtils > testDownloadFromHTTP() FAILED
    java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:293)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:465)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:560)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1572)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at org.apache.commons.io.CloseableURLConnection.getInputStream(CloseableURLConnection.java:177)
        at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1080)
        at org.apache.gravitino.catalog.hive.FetchFileUtils.fetchFileFromUri(FetchFileUtils.java:46)
        at org.apache.gravitino.catalog.hive.TestFetchFileUtils.testDownloadFromHTTP(TestFetchFileUtils.java:46)
```

**Comment by Naresh-kumar-Thodupunoori** [comment]
@FANNG1 may I work on this!

**Comment by FANNG1** [comment]
> @FANNG1 may I work on this!

sure

**Comment by Naresh-kumar-Thodupunoori** [comment]
@FANNG1 
Execution failed for task ':catalogs:catalog-hive:spotlessJava'.
> java.lang.Exception: You are not using latest version on JVM 11+.
  Try to upgrade to google-java-format 1.15.0, which may have fixed this problem.

**Comment by Naresh-kumar-Thodupunoori** [comment]
But in the gradle build file, they have mentioned not to upgrade the version. What should I do now?

**Comment by FANNG1** [comment]
> But in the gradle build file, they have mentioned not to upgrade the version. What should I do now?

I'm not sure,  may be you could try Java 17

**Comment by Naresh-kumar-Thodupunoori** [comment]
Hi @FANNG1 can you go through my PR. I have done it using JAVA 17 and tested it by building in my local and it passed.

**Comment by jerqi** [comment]
@FANNG1 Maybe you can close this. Because the related pull request is merged.

**Comment by FANNG1** [comment]
> @FANNG1 Maybe you can close this. Because the related pull request is merged.

yes, thanks for notification,  the issue is not closed automatically because the PR using `**Fix**`
