### ISSUE TITLE
[Bug report] CI: trino-connector:test FAILED on Cron Integration Test 20240820

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4603]
### Version

main branch

### Describe what's wrong

```
> Task :integration-test:test
Current project version: 0.7.0-incubating-SNAPSHOT
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.hadoop.security.authentication.util.KerberosUtil (file:/root/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-auth/2.10.2/29ab697d6b925ed3a52b782554d59e3312c94572/hadoop-auth-2.10.2.jar) to method sun.security.krb5.Config.getInstance()
WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.security.authentication.util.KerberosUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :trino-connector:test FAILED

:trino-connector:test failure marker
  Error: Execution failed for task ':trino-connector:test':
      org.gradle.api.internal.exceptions.MarkedVerificationException: There were failing tests. See the report at: file:///actions-runner/_work/gravitino-test/gravitino-test/gravitino/build/reports/index.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
129 actionable tasks: 72 executed, 57 up-to-date
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':trino-connector:test'.
> There were failing tests. See the report at: file:///actions-runner/_work/gravitino-test/gravitino-test/gravitino/build/reports/index.html

* Try:
> Run with --scan to get full insights.

BUILD FAILED in 14m 8s

```

### Error message and/or stacktrace

```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 14.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:64)
	at java.base@17.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.12/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.12/java.lang.reflect.Method.invoke(Method.java:569)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy2/jdk.proxy2.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at io.trino.tpch.TextPool$ByteArrayBuilder.<init>(TextPool.java:190)
	at io.trino.tpch.TextPool.<init>(TextPool.java:51)
	at io.trino.tpch.TextPool.<init>(TextPool.java:43)
	at io.trino.tpch.TextPool.lambda$static$0(TextPool.java:31)
	at io.trino.tpch.TextPool$$Lambda$3255/0x000072be010042c8.get(Unknown Source)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
	at io.trino.tpch.TextPool.getDefaultTextPool(TextPool.java:35)
	at io.trino.tpch.OrderGenerator.<init>(OrderGenerator.java:65)
	at io.trino.tpch.TpchTable$2.createGenerator(TpchTable.java:40)
	at io.trino.plugin.tpch.TpchRecordSet.createTpchRecordSet(TpchRecordSet.java:71)
	at io.trino.plugin.tpch.TpchRecordSet.createTpchRecordSet(TpchRecordSet.java:48)
	at io.trino.testing.H2QueryRunner.insertRows(H2QueryRunner.java:181)
	at io.trino.testing.H2QueryRunner.<init>(H2QueryRunner.java:113)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:128)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:70)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor$$Lambda$423/0x000072be001860d0.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall$$Lambda$206/0x000072be0013f250.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$$Lambda$376/0x000072be0016ece0.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
```

### How to reproduce

Cron Github Action:
https://github.com/datastrato/gravitino-test/actions/runs/10477629581/job/29019254226

**Comment by danhuawang** [comment]
@diqiu50 Would you like to help trouble shooting this issue on cron CI ?
