### ISSUE TITLE
[Bug report] CI: test containers initialization error  on Cron Integration Test 20240822

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4640]
### Version

main branch

### Describe what's wrong

<img width="779" alt="image" src="https://github.com/user-attachments/assets/c4c32045-883e-49de-97c1-2502b7f73a6b">

### Error message and/or stacktrace

```
> Task :integration-test:test

TagIT > initializationError FAILED
    org.testcontainers.shaded.org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.apache.gravitino.integration.test.util.AbstractIT that uses java.lang.String was not fulfilled within 1 minutes.
        at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
        at org.testcontainers.shaded.org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
        at org.testcontainers.shaded.org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
        at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
        at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
        at org.apache.gravitino.integration.test.util.AbstractIT.startIntegrationTest(AbstractIT.java:257)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:68)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllMethods$11(ClassBasedTestDescriptor.java:397)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllMethods(ClassBasedTestDescriptor.java:395)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:209)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at 
```

### How to reproduce

Cron Github Action:
https://github.com/datastrato/gravitino-test/actions/runs/10514085356/job/29131196920

**Comment by danhuawang** [comment]
@mchades  Would you like to help check this problem ? Thanks!

**Comment by mchades** [comment]
It's because the Gravitino server does not start up successfully:

> Exception in thread "main" java.lang.NoSuchMethodError: 'java.util.Map javax.ws.rs.core.Application.getProperties()'
> 	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:311)
> 	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:297)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
> 	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
> 	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:296)
> 	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:261)
> 	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
> 	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
> 	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:339)
> 	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
> 	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:632)
> 	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:415)
> 	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
> 	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)

I think this is due to a dependency conflict introduced by the ranger authorization, which should be fixable by #4651 , as in that PR the dependencies of ranger will be placed in a separate directory.

**Comment by mchades** [comment]
#4651 was merged, can you verify again if this issue has been fixed? @danhuawang
