### ISSUE TITLE
[Bug report] Gravitino client and Gravitino server should be compatible with minor version differences 

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#4707]
### Version

main branch

### Describe what's wrong

If the client version is 0.6.1 and the server version is 0.6.0,  in this case, client should be compatible with server. the client should be compatible with the 

### Error message and/or stacktrace

ERROR [gravitino-connector-schedule-0] CatalogConnectorManager:133 - Load Metalake metalake_demo failed.
playground-trino       | org.apache.gravitino.exceptions.GravitinoRuntimeException: Gravitino does not support the case that the client-side version is higher than the server-side version.The client version is 0.6.1-incubating-SNAPSHOT, and the server version 0.6.0-incubating
playground-trino       |        at org.apache.gravitino.client.GravitinoClientBase.checkVersion(GravitinoClientBase.java:105) ~[gravitino-client-java-runtime-0.6.1-incubating-SNAPSHOT.jar:?]
playground-trino       |        at org.apache.gravitino.client.HTTPClient.performPreConnectHandler(HTTPClient.java:410) ~[gravitino-client-java-runtime-0.6.1-incubating-SNAPSHOT.jar:?]
pla

### How to reproduce

Please see above

**Comment by shaofengshi** [comment]
It said: "Gravitino does not support the case that the client-side version is higher than the server-side version.The client version is 0.6.1-incubating-SNAPSHOT, and the server version 0.6.0-incubating"

Is this by design?
