### ISSUE TITLE
[Bug report] Improper error message for Paimon catalog with a wrong warehouse address

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#4841]
### Version

main branch

### Describe what's wrong

When We try to create a schema under a paimon using command:

```shell
curl -X POST -H "Content-Type: application/json" -d '{"name":"paimon_catalog3","comment":"my test catalog","type":"RELATIONAL","provider":"lakehouse-paimon","properties":{"catalog-backend":"filesystem","uri":"thrift://localhost:9083","warehouse":"/wrong_address"}}' http://localhost:8090/api/metalakes/test/catalogs

curl -X POST -H "Content-Type: application/json" -d '{"name":"db","comment":"comment"}' http://localhost:8090/api/metalakes/test/catalogs/paimon_catalog3/schemas

```

Then we will get the following error:
```text
{"code":1003,"type":"NoSuchSchemaException","message":"Failed to operate schema(s) [db] operation [CREATE] under catalog [paimon_catalog3], reason [Paimon schema (database) test.paimon_catalog3.db does not exist.]","stack":["org.apache.gravitino.exceptions.NoSuchSchemaException: Paimon schema (database) test.paimon_catalog3.db does not exist.","\tat org.apache.gravitino.catalog.lakehouse.paimon.PaimonCatalogOperations.loadSchema(PaimonCatalogOperations.java:211)","\tat org.apache.gravitino.catalog.lakehouse.paimon.PaimonCatalogOperations.loadSchema(PaimonCatalogOperations.java:78)","\tat org.apache.gravitino.catalog.SchemaOperationDispatcher.lambda$createSchema$6(SchemaOperationDispatcher.java:136)","\tat org.apache.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithSchemaOps$0(CatalogManager.java:122)","\tat org.apache.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:86)","\tat org.apache.gravitino.catalog.CatalogManager$CatalogWrapper.doWithSchemaOps(CatalogManager.java:117)","\tat org.apache.gravitino.catalog.SchemaOperationDispatcher.lambda$createSchema$7(SchemaOperationDispatcher.java:136)","\tat org.apache.gravitino.catalog.OperationDispatcher.doWithCatalog(OperationDispatcher.java:97)","\tat org.apache.gravitino.catalog.SchemaOperationDispatcher.createSchema(SchemaOperationDispatcher.java:134)","\tat org.apache.gravitino.hook.SchemaHookDispatcher.createSchema(SchemaHookDispatcher.java:58)","\tat org.apache.gravitino.catalog.SchemaNormalizeDispatcher.createSchema(SchemaNormalizeDispatcher.java:64)","\tat org.apache.gravitino.listener.SchemaEventDispatcher.createSchema(SchemaEventDispatcher.java:90)","\tat org.apache.gravitino.server.web.rest.SchemaOperations.lambda$createSchema$2(SchemaOperations.java:122)","\tat org.apache.gravitino.lock.TreeLockUtils.doWithTreeLock(TreeLockUtils.java:49)","\tat org.apache.gravitino.server.web.rest.SchemaOperations.lambda$createSchema$3(SchemaOperations.java:118)","\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
```

### Error message and/or stacktrace

2024-09-03 15:34:00.983 INFO [tree-lock-dead-lock-checker-0] [org.apache.gravitino.lock.LockManager.lambda$startDeadLockChecker$0(LockManager.java:116)] - Finish to check the dead lock...
2024-09-03 15:34:00.985 WARN [Gravitino-webserver-24] [org.apache.paimon.catalog.FileSystemCatalog.createDatabaseImpl(FileSystemCatalog.java:83)] - Currently filesystem catalog can't store database properties, discard properties: {gravitino.identifier=gravitino.v1.uid2504549464292755707}
2024-09-03 15:34:00.988 INFO [Gravitino-webserver-24] [org.apache.gravitino.catalog.lakehouse.paimon.PaimonCatalogOperations.createSchema(PaimonCatalogOperations.java:189)] - Created Paimon schema (database): test.paimon_catalog.db. Current user: anonymous. Comment: comment. Metadata: {gravitino.identifier=gravitino.v1.uid2504549464292755707}.
2024-09-03 15:34:03.040 WARN [Gravitino-webserver-24] [org.apache.gravitino.server.web.rest.ExceptionHandlers$SchemaExceptionHandler.handle(ExceptionHandlers.java:231)] - Failed to operate schema(s) [db] operation [CREATE] under catalog [paimon_catalog], reason [Paimon schema (database) test.paimon_catalog.db does not exist.]
org.apache.gravitino.exceptions.NoSuchSchemaException: Paimon schema (database) test.paimon_catalog.db does not exist.
	at org.apache.gravitino.catalog.lakehouse.paimon.PaimonCatalogOperations.loadSchema(PaimonCatalogOperations.java:211) ~[?:?]
	at org.apache.gravitino.catalog.lakehouse.paimon.PaimonCatalogOperations.loadSchema(PaimonCatalogOperations.java:78) ~[?:?]
	at org.apache.gravitino.catalog.SchemaOperationDispatcher.lambda$createSchema$6(SchemaOperationDispatcher.java:136) ~[gravitino-core-0.6.0-incubating.jar:?]
	at org.apache.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithSchemaOps$0(CatalogManager.java:122) ~[gravitino-core-0.6.0-incubating.jar:?]
	at org.apache.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:86) ~[gravitino-core-0.6.0-incubating.jar:?]
	at org.apache.gravitino.catalog.CatalogManager$CatalogWrapper.doWithSchemaOps(CatalogManager.java:117) ~[gravitino-core-0.6.0-incubating.jar:?]
	at org.apache.gravitino.catalog.SchemaOperationDispatcher.lambda$createSchema$7(SchemaOperationDispatcher.java:136) ~[gravitino-core-0.6.0-incubating.jar:?]
	at org.apache.gravitino.catalog.OperationDispatcher.doWithCatalog(OperationDispatcher.java:97) ~[gravitino-core-0.6.0-incubating.jar:?]
	at org.apache.gravitino.catalog.SchemaOperationDispatcher.createSchema(SchemaOperationDispatcher.java:134) ~[gravitino-core-0.6.0-incubating.jar:?]
	at org.apache.gravitino.hook.SchemaHookDispatcher.createSchema(SchemaHookDispatcher.java:58) ~[gravitino-core-0.6.0-incubating.jar:?]
	at org.apache.gravitino.catalog.SchemaNormalizeDispatcher.createSchema(SchemaNormalizeDispatcher.java:64) ~[gravitino-core-0.6.0-incubating.jar:?]
	at org.apache.gravitino.listener.SchemaEventDispatcher.createSchema(SchemaEventDispatcher.java:90) ~[gravitino-core-0.6.0-incubating.jar:?]
	at org.apache.gravitino.server.web.rest.SchemaOperations.lambda$createSchema$2(SchemaOperations.java:122) ~[gravitino-server-0.6.0-incubating.jar:?]
	at org.apache.gravitino.lock.TreeLockUtils.doWithTreeLock(TreeLockUtils.java:49) ~[gravitino-core-0.6.0-incubating.jar:?]
	at org.apache.gravitino.server.web.rest.SchemaOperations.lambda$createSchema$3(SchemaOperations.java:118) ~[gravitino-server-0.6.0-incubating.jar:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	at java.base/javax.security.auth.Subject.doAs(Subject.java:439) ~[?:?]
	at org.apache.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:39) ~[gravitino-core-0.6.0-incubating.jar:?]
	at org.apache.gravitino.server.web.Utils.doAs(Utils.java:149) ~[gravitino-server-0.6.0-incubating.jar:?]
	at org.apache.gravitino.server.web.rest.SchemaOperations.createSchema(SchemaOperations.java:111) ~[gravitino-server-0.6.0-incubating.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.apache.gravitino.server.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:86) ~[gravitino-server-common-0.6.0-incubating.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.apache.gravitino.server.web.VersioningFilter.doFilter(VersioningFilter.java:123) ~[gravitino-server-0.6.0-incubating.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[jetty-security-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.apache.gravitino.server.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:86) ~[gravitino-server-common-0.6.0-incubating.jar:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.apache.gravitino.server.web.VersioningFilter.doFilter(VersioningFilter.java:123) ~[gravitino-server-0.6.0-incubating.jar:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[jetty-security-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.apache.paimon.catalog.Catalog$DatabaseNotExistException: Database db does not exist.
        at org.apache.paimon.catalog.AbstractCatalog.loadDatabaseProperties(AbstractCatalog.java:160) ~[?:?]
        at org.apache.gravitino.catalog.lakehouse.paimon.ops.PaimonCatalogOps.loadDatabase(PaimonCatalogOps.java:67) ~[?:?]
        at org.apache.gravitino.catalog.lakehouse.paimon.PaimonCatalogOperations.loadSchema(PaimonCatalogOperations.java:209) ~[?:?]
        ... 85 more

### How to reproduce

Please see above.

**Comment by FANNG1** [comment]
seems a bug of Paimon, will be fixed by https://github.com/apache/paimon/pull/4399

**Comment by FANNG1** [comment]
It mainly affects the local filesystem

**Comment by FANNG1** [comment]
will be fixed in the next release of Paimon. cc @jerryshao

**Comment by FANNG1** [comment]
moved to 0.8

**Comment by jerryshao** [comment]
@FANNG1 please work on this when you have time.

**Comment by FANNG1** [comment]
This is fixed in Paimon 1.0, I wonder whether should we wait a moment for an more stable release for Paimon, and this issue is an minor issue.

**Comment by jerryshao** [comment]
OK, this seems reasonable, can you please remove the `0.8.0` label.

**Comment by yuqi1129** [comment]
> seems a bug of Paimon, will be fixed by [apache/paimon#4399](https://github.com/apache/paimon/pull/4399)

This has been merged, so we close it.
