### ISSUE TITLE
[Bug report] run trino_test.sh failed caused by: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4902]
### Version

main branch

### Describe what's wrong

```
 ./trino_test.sh --auto=none --ignore_failed --postgresql_uri=jdbc:postgresql://pg-16-postgresql.relational-catalog:5432 --mysql_uri=jdbc:mysql://my-8-mysql.relational-catalog:3306 --hdfs_uri=hdfs://hadoop-hdfs-namenode.hadoop:8020 --hive_uri=thrift://hadoop-metastore.hadoop:9083 --gravitino_uri=http://acbf7865e0d30481aa58f235fd948699-1191993091.***.elb.amazonaws.com:8090 --trino_uri=http://a1832a74201584926a2ab66ee6244c26-1323897966.***.elb.amazonaws.com:8080   


  > Task :trino-connector:integration-test:compileTestJava
Note: /actions-runner/_work/gravitino-test/gravitino-test/gravitino/trino-connector/integration-test/src/test/java/org/apache/gravitino/trino/connector/integration/test/TrinoQueryIT.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :trino-connector:integration-test:testClasses

> Task :trino-connector:integration-test:TrinoTest FAILED
Error: Could not find or load main class org.apache.gravitino.integration.test.trino.TrinoQueryTestTool
Caused by: java.lang.ClassNotFoundException: org.apache.gravitino.integration.test.trino.TrinoQueryTestTool
:trino-connector:integration-test:TrinoTest failure marker
  Error: Execution failed for task ':trino-connector:integration-test:TrinoTest':
      org.gradle.process.internal.ExecException: Process 'command '/actions-runner/_work/_tool/Java_Temurin-Hotspot_jdk/17.0.12-7/x64/bin/java'' finished with non-zero exit value 1
          at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:415)
          at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:52)
          at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:165)
          at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
          at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
          at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
          at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
          at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:248)
          at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
          at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
          at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
          at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
          at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
          at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
          at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
          at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:233)
          at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:216)
          at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:199)
          at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:166)
          at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
          at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
          at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
          at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
          at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
          at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
          at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
          at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
          at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
          at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
          at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
          at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
          at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
          at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
          at org.gradle.internal.execution.steps.RemovePreviousOutpu

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':trino-connector:integration-test:TrinoTest'.
> Process 'command '/actions-runner/_work/_tool/Java_Temurin-Hotspot_jdk/17.0.12-7/x64/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 4m 12s
```

### Error message and/or stacktrace

see above

### How to reproduce

 ./trino_test.sh --auto=none --ignore_failed --postgresql_uri=jdbc:postgresql://pg-16-postgresql.relational-catalog:5432 --mysql_uri=jdbc:mysql://my-8-mysql.relational-catalog:3306 --hdfs_uri=hdfs://hadoop-hdfs-namenode.hadoop:8020 --hive_uri=thrift://hadoop-metastore.hadoop:9083 --gravitino_uri=http://***:8090 --trino_uri=http://***:8080

**Comment by diqiu50** [comment]
Fixed
