### ISSUE TITLE
[Bug report] HMS HA Feature unsupported

### ISSUE THREAD

**Issue by xxzhky** [apache/gravitino#5137]
### Version

0.6.0

### Describe what's wrong

<meta charset="utf-8"><div data-page-id="NTGKdrzL9o9Sy4x6kQxcsHxen9b" data-lark-html-role="root" data-docx-has-block-data="true"><h1 class="heading-1 ace-line old-record-id-E6ZHd0vjXoH7OLxLU2Pcu68hn4b">Gravitino catalog config</h1><div class="ace-line ace-line old-record-id-LhXddrUdToWyCRxRaiccKvuunQh">Properties</div><div data-type="sheet" class=" old-record-id-S1e0dhWIGochINxyLf0chwMUn2c"><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style> td {white-space:nowrap;border:1px solid #dee0e3;font-size:10pt;font-style:normal;font-weight:normal;vertical-align:middle;word-break:normal;word-wrap:normal;}</style><byte-sheet-html-origin data-id="" data-version="4" data-is-embed="true" data-grid-line-hidden="false" data-copy-type="col">
Key | Value
-- | --
gravitino.bypass.hive.metastore.client.capability.check | FALSE
metastore.uris | thrift://ecs-dev-66-133-flink.msxf.host:9089,thrift://ecs-dev-66-100-flink.msxf.host:9089
kerberos.principal | hive/ecs-dev-64-179-flink.msxf.host@DPOPSTEST.HADOOP
gravitino.bypass.hive.metastore.kerberos.principal | hive/ecs-dev-66-133-flink.msxf.host@DPOPSTEST.HADOOP
kerberos.keytab-uri | file:///home/xdt/gravikey/hms4/hive.keytab
gravitino.bypass.hive.metastore.sasl.enabled | TRUE
gravitino.bypass.hadoop.security.authentication | kerberos

</byte-sheet-html-origin></div><h1 class="heading-1 ace-line old-record-id-ZjWtdA1dlovqLQxkchAcHrnXnwh">Reason</h1><div class="ace-line ace-line old-record-id-XgC1dBvQNoet6pxTQKeci9ftnRg">When configuring the Iceberg catalog, attempting to use multiple Hive Metastore instances to meet the production environment's high-availability (HA) requirements results in the following error:</div><pre style="white-space:pre;" class="ace-line ace-line old-record-id-KToYdfqXpoE1c7xIz8NczOHZnpc"><code class="language-Plain Text" data-lark-language="Plain Text" data-wrap="false"><div>transport.TSaslTransport: SASL negotiation failure
javax.security.sasl.SaslException: GSS initiate failed</div></code></pre><div class="ace-line ace-line old-record-id-AP9idgReyoWZMvxISvVc84HPnCd"><strong>Note:</strong></div><div class="ace-line ace-line old-record-id-NDX1dzZZtoQwcaxC2YNcu2IIn6c">For the relevant catalog configuration information, please refer to the table above. Specifically:</div><ul start="1" class="list-bullet1"><li class="ace-line ace-line old-record-id-WDezdEEmToWpNSx1AxkcTBMVnSe" data-list="bullet"><div><code>metastore.uris</code> is configured with two instances.</div></li><li class="ace-line ace-line old-record-id-D6kTd5YgooUkHPxOYGwcZt5snOe" data-list="bullet"><div><code>gravitino.bypass.hive.metastore.kerberos.principal</code> is configured with two principals.</div></li></ul></div><span data-lark-record-data="{&quot;isCut&quot;:false,&quot;rootId&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;,&quot;parentId&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;,&quot;blockIds&quot;:[355,357,358,359,366,368,370,371,372,373],&quot;recordIds&quot;:[&quot;E6ZHd0vjXoH7OLxLU2Pcu68hn4b&quot;,&quot;LhXddrUdToWyCRxRaiccKvuunQh&quot;,&quot;S1e0dhWIGochINxyLf0chwMUn2c&quot;,&quot;ZjWtdA1dlovqLQxkchAcHrnXnwh&quot;,&quot;XgC1dBvQNoet6pxTQKeci9ftnRg&quot;,&quot;KToYdfqXpoE1c7xIz8NczOHZnpc&quot;,&quot;AP9idgReyoWZMvxISvVc84HPnCd&quot;,&quot;NDX1dzZZtoQwcaxC2YNcu2IIn6c&quot;,&quot;WDezdEEmToWpNSx1AxkcTBMVnSe&quot;,&quot;D6kTd5YgooUkHPxOYGwcZt5snOe&quot;],&quot;recordMap&quot;:{&quot;E6ZHd0vjXoH7OLxLU2Pcu68hn4b&quot;:{&quot;id&quot;:&quot;E6ZHd0vjXoH7OLxLU2Pcu68hn4b&quot;,&quot;snapshot&quot;:{&quot;comments&quot;:[],&quot;hidden&quot;:false,&quot;align&quot;:&quot;&quot;,&quot;type&quot;:&quot;heading1&quot;,&quot;parent_id&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;,&quot;locked&quot;:false,&quot;author&quot;:&quot;7397307892162002946&quot;,&quot;children&quot;:[],&quot;text&quot;:{&quot;initialAttributedTexts&quot;:{&quot;text&quot;:{&quot;0&quot;:&quot;Gravitino catalog config&quot;},&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+o&quot;}},&quot;apool&quot;:{&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7397307892162002946&quot;]},&quot;nextNum&quot;:1}},&quot;folded&quot;:false}},&quot;LhXddrUdToWyCRxRaiccKvuunQh&quot;:{&quot;id&quot;:&quot;LhXddrUdToWyCRxRaiccKvuunQh&quot;,&quot;snapshot&quot;:{&quot;align&quot;:&quot;&quot;,&quot;comments&quot;:[],&quot;children&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7397307892162002946&quot;,&quot;text&quot;:{&quot;initialAttributedTexts&quot;:{&quot;text&quot;:{&quot;0&quot;:&quot;Properties&quot;},&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+a&quot;}},&quot;apool&quot;:{&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7397307892162002946&quot;]},&quot;nextNum&quot;:1}},&quot;folded&quot;:false,&quot;type&quot;:&quot;text&quot;,&quot;parent_id&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;}},&quot;S1e0dhWIGochINxyLf0chwMUn2c&quot;:{&quot;id&quot;:&quot;S1e0dhWIGochINxyLf0chwMUn2c&quot;,&quot;snapshot&quot;:{&quot;type&quot;:&quot;sheet&quot;,&quot;parent_id&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7397307892162002946&quot;,&quot;token&quot;:&quot;VHYOsrmAihEYJNt7hcScVuJinbc_sIeVJY&quot;}},&quot;ZjWtdA1dlovqLQxkchAcHrnXnwh&quot;:{&quot;id&quot;:&quot;ZjWtdA1dlovqLQxkchAcHrnXnwh&quot;,&quot;snapshot&quot;:{&quot;type&quot;:&quot;heading1&quot;,&quot;parent_id&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;,&quot;folded&quot;:false,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7397307892162002946&quot;,&quot;children&quot;:[],&quot;text&quot;:{&quot;initialAttributedTexts&quot;:{&quot;text&quot;:{&quot;0&quot;:&quot;Reason&quot;},&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+6&quot;}},&quot;apool&quot;:{&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7397307892162002946&quot;]},&quot;nextNum&quot;:1}},&quot;align&quot;:&quot;&quot;}},&quot;XgC1dBvQNoet6pxTQKeci9ftnRg&quot;:{&quot;id&quot;:&quot;XgC1dBvQNoet6pxTQKeci9ftnRg&quot;,&quot;snapshot&quot;:{&quot;children&quot;:[],&quot;align&quot;:&quot;&quot;,&quot;folded&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7397307892162002946&quot;,&quot;text&quot;:{&quot;initialAttributedTexts&quot;:{&quot;text&quot;:{&quot;0&quot;:&quot;When configuring the Iceberg catalog, attempting to use multiple Hive Metastore instances to meet the production environment's high-availability (HA) requirements results in the following error:&quot;},&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+5e&quot;}},&quot;apool&quot;:{&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7397307892162002946&quot;]},&quot;nextNum&quot;:1}},&quot;type&quot;:&quot;text&quot;,&quot;parent_id&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false}},&quot;KToYdfqXpoE1c7xIz8NczOHZnpc&quot;:{&quot;id&quot;:&quot;KToYdfqXpoE1c7xIz8NczOHZnpc&quot;,&quot;snapshot&quot;:{&quot;text&quot;:{&quot;initialAttributedTexts&quot;:{&quot;text&quot;:{&quot;0&quot;:&quot;transport.TSaslTransport: SASL negotiation failure\njavax.security.sasl.SaslException: GSS initiate failed&quot;},&quot;attribs&quot;:{&quot;0&quot;:&quot;*0|1+1f*0+1i&quot;}},&quot;apool&quot;:{&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7397307892162002946&quot;]},&quot;nextNum&quot;:1}},&quot;align&quot;:&quot;&quot;,&quot;wrap&quot;:false,&quot;parent_id&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;,&quot;author&quot;:&quot;7397307892162002946&quot;,&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;children&quot;:[],&quot;language&quot;:&quot;Plain Text&quot;,&quot;type&quot;:&quot;code&quot;,&quot;comments&quot;:[]}},&quot;AP9idgReyoWZMvxISvVc84HPnCd&quot;:{&quot;id&quot;:&quot;AP9idgReyoWZMvxISvVc84HPnCd&quot;,&quot;snapshot&quot;:{&quot;comments&quot;:[],&quot;hidden&quot;:false,&quot;author&quot;:&quot;7397307892162002946&quot;,&quot;children&quot;:[],&quot;align&quot;:&quot;&quot;,&quot;type&quot;:&quot;text&quot;,&quot;parent_id&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;,&quot;folded&quot;:false,&quot;locked&quot;:false,&quot;text&quot;:{&quot;initialAttributedTexts&quot;:{&quot;text&quot;:{&quot;0&quot;:&quot;Note:&quot;},&quot;attribs&quot;:{&quot;0&quot;:&quot;*0*1+5&quot;}},&quot;apool&quot;:{&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7397307892162002946&quot;],&quot;1&quot;:[&quot;bold&quot;,&quot;true&quot;]},&quot;nextNum&quot;:2}}}},&quot;NDX1dzZZtoQwcaxC2YNcu2IIn6c&quot;:{&quot;id&quot;:&quot;NDX1dzZZtoQwcaxC2YNcu2IIn6c&quot;,&quot;snapshot&quot;:{&quot;author&quot;:&quot;7397307892162002946&quot;,&quot;children&quot;:[],&quot;align&quot;:&quot;&quot;,&quot;folded&quot;:false,&quot;type&quot;:&quot;text&quot;,&quot;parent_id&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;text&quot;:{&quot;initialAttributedTexts&quot;:{&quot;text&quot;:{&quot;0&quot;:&quot;For the relevant catalog configuration information, please refer to the table above. Specifically:&quot;},&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+2q&quot;}},&quot;apool&quot;:{&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7397307892162002946&quot;]},&quot;nextNum&quot;:1}}}},&quot;WDezdEEmToWpNSx1AxkcTBMVnSe&quot;:{&quot;id&quot;:&quot;WDezdEEmToWpNSx1AxkcTBMVnSe&quot;,&quot;snapshot&quot;:{&quot;hidden&quot;:false,&quot;folded&quot;:false,&quot;type&quot;:&quot;bullet&quot;,&quot;locked&quot;:false,&quot;children&quot;:[],&quot;text&quot;:{&quot;initialAttributedTexts&quot;:{&quot;text&quot;:{&quot;0&quot;:&quot;metastore.uris is configured with two instances.&quot;},&quot;attribs&quot;:{&quot;0&quot;:&quot;*0*1+e*0+y&quot;}},&quot;apool&quot;:{&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7397307892162002946&quot;],&quot;1&quot;:[&quot;inlineCode&quot;,&quot;true&quot;]},&quot;nextNum&quot;:2}},&quot;align&quot;:&quot;&quot;,&quot;parent_id&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;,&quot;comments&quot;:[],&quot;author&quot;:&quot;7397307892162002946&quot;}},&quot;D6kTd5YgooUkHPxOYGwcZt5snOe&quot;:{&quot;id&quot;:&quot;D6kTd5YgooUkHPxOYGwcZt5snOe&quot;,&quot;snapshot&quot;:{&quot;author&quot;:&quot;7397307892162002946&quot;,&quot;text&quot;:{&quot;initialAttributedTexts&quot;:{&quot;text&quot;:{&quot;0&quot;:&quot;gravitino.bypass.hive.metastore.kerberos.principal is configured with two principals.&quot;},&quot;attribs&quot;:{&quot;0&quot;:&quot;*0*1+1e*0+z&quot;}},&quot;apool&quot;:{&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7397307892162002946&quot;],&quot;1&quot;:[&quot;inlineCode&quot;,&quot;true&quot;]},&quot;nextNum&quot;:2}},&quot;align&quot;:&quot;&quot;,&quot;folded&quot;:false,&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;comments&quot;:[],&quot;children&quot;:[],&quot;type&quot;:&quot;bullet&quot;,&quot;parent_id&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;}},&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;:{&quot;id&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;,&quot;snapshot&quot;:{&quot;revisions&quot;:null,&quot;children&quot;:[&quot;E6ZHd0vjXoH7OLxLU2Pcu68hn4b&quot;,&quot;LhXddrUdToWyCRxRaiccKvuunQh&quot;,&quot;S1e0dhWIGochINxyLf0chwMUn2c&quot;,&quot;ZjWtdA1dlovqLQxkchAcHrnXnwh&quot;,&quot;XgC1dBvQNoet6pxTQKeci9ftnRg&quot;,&quot;KToYdfqXpoE1c7xIz8NczOHZnpc&quot;,&quot;AP9idgReyoWZMvxISvVc84HPnCd&quot;,&quot;NDX1dzZZtoQwcaxC2YNcu2IIn6c&quot;,&quot;WDezdEEmToWpNSx1AxkcTBMVnSe&quot;,&quot;D6kTd5YgooUkHPxOYGwcZt5snOe&quot;,&quot;SATXdKUK8or3OYxGjQ2c8nCjnNd&quot;,&quot;XK8JdHtOpodwANx0D46cIoeMnte&quot;,&quot;HW4Ed2NoZop1C2xyoKzcfhaXnue&quot;,&quot;V9lTdN97Lon3H0xav97czpgkn8d&quot;,&quot;RkCEdRE92ojzJjxXNoWcEFKznog&quot;],&quot;text&quot;:{&quot;apool&quot;:{&quot;nextNum&quot;:1,&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7397307892162002946&quot;]}},&quot;initialAttributedTexts&quot;:{&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+q&quot;},&quot;text&quot;:{&quot;0&quot;:&quot;HMS HA Feature unsupported&quot;}}},&quot;align&quot;:&quot;&quot;,&quot;type&quot;:&quot;page&quot;,&quot;parent_id&quot;:&quot;&quot;,&quot;comments&quot;:null,&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7397307892162002946&quot;,&quot;doc_info&quot;:{&quot;option_modified&quot;:null,&quot;editors&quot;:[&quot;7397307892162002946&quot;],&quot;options&quot;:[&quot;editors&quot;,&quot;edit_time&quot;],&quot;deleted_editors&quot;:null}}}},&quot;payloadMap&quot;:{&quot;LhXddrUdToWyCRxRaiccKvuunQh&quot;:{&quot;level&quot;:1},&quot;XgC1dBvQNoet6pxTQKeci9ftnRg&quot;:{&quot;level&quot;:1},&quot;AP9idgReyoWZMvxISvVc84HPnCd&quot;:{&quot;level&quot;:1},&quot;NDX1dzZZtoQwcaxC2YNcu2IIn6c&quot;:{&quot;level&quot;:1},&quot;lingoClipboardPayload&quot;:{&quot;spaceSubExtraInfo&quot;:[{&quot;spaceSubId&quot;:&quot;XgC1dBvQNoet6pxTQKeci9ftnRg&quot;,&quot;word&quot;:&quot;HA&quot;}],&quot;spaceId&quot;:&quot;NTGKdrzL9o9Sy4x6kQxcsHxen9b&quot;,&quot;spaceType&quot;:1}},&quot;extra&quot;:{&quot;channel&quot;:&quot;saas&quot;,&quot;pasteRandomId&quot;:&quot;1c46b7e5-d136-47a7-b364-0a432b16b824&quot;,&quot;mention_page_title&quot;:{},&quot;external_mention_url&quot;:{}},&quot;isKeepQuoteContainer&quot;:false,&quot;selection&quot;:[{&quot;id&quot;:355,&quot;type&quot;:&quot;text&quot;,&quot;selection&quot;:{&quot;start&quot;:0,&quot;end&quot;:24},&quot;recordId&quot;:&quot;E6ZHd0vjXoH7OLxLU2Pcu68hn4b&quot;},{&quot;id&quot;:357,&quot;type&quot;:&quot;text&quot;,&quot;selection&quot;:{&quot;start&quot;:0,&quot;end&quot;:10},&quot;recordId&quot;:&quot;LhXddrUdToWyCRxRaiccKvuunQh&quot;},{&quot;id&quot;:358,&quot;type&quot;:&quot;block&quot;,&quot;recordId&quot;:&quot;S1e0dhWIGochINxyLf0chwMUn2c&quot;},{&quot;id&quot;:359,&quot;type&quot;:&quot;text&quot;,&quot;selection&quot;:{&quot;start&quot;:0,&quot;end&quot;:6},&quot;recordId&quot;:&quot;ZjWtdA1dlovqLQxkchAcHrnXnwh&quot;},{&quot;id&quot;:366,&quot;type&quot;:&quot;text&quot;,&quot;selection&quot;:{&quot;start&quot;:0,&quot;end&quot;:194},&quot;recordId&quot;:&quot;XgC1dBvQNoet6pxTQKeci9ftnRg&quot;},{&quot;id&quot;:368,&quot;type&quot;:&quot;block&quot;,&quot;recordId&quot;:&quot;KToYdfqXpoE1c7xIz8NczOHZnpc&quot;},{&quot;id&quot;:370,&quot;type&quot;:&quot;text&quot;,&quot;selection&quot;:{&quot;start&quot;:0,&quot;end&quot;:5},&quot;recordId&quot;:&quot;AP9idgReyoWZMvxISvVc84HPnCd&quot;},{&quot;id&quot;:371,&quot;type&quot;:&quot;text&quot;,&quot;selection&quot;:{&quot;start&quot;:0,&quot;end&quot;:98},&quot;recordId&quot;:&quot;NDX1dzZZtoQwcaxC2YNcu2IIn6c&quot;},{&quot;id&quot;:372,&quot;type&quot;:&quot;text&quot;,&quot;selection&quot;:{&quot;start&quot;:0,&quot;end&quot;:48},&quot;recordId&quot;:&quot;WDezdEEmToWpNSx1AxkcTBMVnSe&quot;},{&quot;id&quot;:373,&quot;type&quot;:&quot;text&quot;,&quot;selection&quot;:{&quot;start&quot;:0,&quot;end&quot;:85},&quot;recordId&quot;:&quot;D6kTd5YgooUkHPxOYGwcZt5snOe&quot;}],&quot;pasteFlag&quot;:&quot;648c8cf3-ea73-49af-b698-bc2a6dea50b7&quot;}" data-lark-record-format="docx/record" class="lark-record-clipboard"></span>

### Error message and/or stacktrace

2024-10-12T10:52:10,393 ERROR [Metastore-Handler-Pool: Thread-63] transport.TSaslTransport: SASL negotiation failure
javax.security.sasl.SaslException: GSS initiate failed
        at com.sun.security.sasl.gsskerb.GssKrb5Server.evaluateResponse(GssKrb5Server.java:199) ~[?:1.8.0_232]
        at org.apache.thrift.transport.TSaslTransport$SaslParticipant.evaluateChallengeOrResponse(TSaslTransport.java:507) ~[hive-exec-4.0.0.jar:4.0.0]
        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:250) ~[hive-exec-4.0.0.jar:4.0.0]
        at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:44) ~[hive-exec-4.0.0.jar:4.0.0]
        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:199) ~[hive-exec-4.0.0.jar:4.0.0]
        at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:711) ~[hive-exec-4.0.0.jar:4.0.0]
        at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:707) ~[hive-exec-4.0.0.jar:4.0.0]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_232]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[?:1.8.0_232]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1855) ~[hadoop-common-3.3.4.jar:?]
        at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory.getTransport(HadoopThriftAuthBridge.java:707) ~[hive-exec-4.0.0.jar:4.0.0]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:227) ~[hive-exec-4.0.0.jar:4.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_232]
Caused by: org.ietf.jgss.GSSException: Failure unspecified at GSS-API level (Mechanism level: Checksum failed)
        at sun.security.jgss.krb5.Krb5Context.acceptSecContext(Krb5Context.java:858) ~[?:1.8.0_232]
        at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:342) ~[?:1.8.0_232]
        at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:285) ~[?:1.8.0_232]
        at com.sun.security.sasl.gsskerb.GssKrb5Server.evaluateResponse(GssKrb5Server.java:167) ~[?:1.8.0_232]
        ... 14 more
Caused by: sun.security.krb5.KrbCryptoException: Checksum failed
        at sun.security.krb5.internal.crypto.Aes128CtsHmacSha1EType.decrypt(Aes128CtsHmacSha1EType.java:102) ~[?:1.8.0_232]
        at sun.security.krb5.internal.crypto.Aes128CtsHmacSha1EType.decrypt(Aes128CtsHmacSha1EType.java:94) ~[?:1.8.0_232]
        at sun.security.krb5.EncryptedData.decrypt(EncryptedData.java:175) ~[?:1.8.0_232]
        at sun.security.krb5.KrbApReq.authenticate(KrbApReq.java:281) ~[?:1.8.0_232]
        at sun.security.krb5.KrbApReq.<init>(KrbApReq.java:149) ~[?:1.8.0_232]
        at sun.security.jgss.krb5.InitSecContextToken.<init>(InitSecContextToken.java:108) ~[?:1.8.0_232]
        at sun.security.jgss.krb5.Krb5Context.acceptSecContext(Krb5Context.java:831) ~[?:1.8.0_232]
        at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:342) ~[?:1.8.0_232]
        at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:285) ~[?:1.8.0_232]
        at com.sun.security.sasl.gsskerb.GssKrb5Server.evaluateResponse(GssKrb5Server.java:167) ~[?:1.8.0_232]
        ... 14 more
Caused by: java.security.GeneralSecurityException: Checksum failed
        at sun.security.krb5.internal.crypto.dk.AesDkCrypto.decryptCTS(AesDkCrypto.java:451) ~[?:1.8.0_232]
        at sun.security.krb5.internal.crypto.dk.AesDkCrypto.decrypt(AesDkCrypto.java:272) ~[?:1.8.0_232]
        at sun.security.krb5.internal.crypto.Aes128.decrypt(Aes128.java:76) ~[?:1.8.0_232]
        at sun.security.krb5.internal.crypto.Aes128CtsHmacSha1EType.decrypt(Aes128CtsHmacSha1EType.java:100) ~[?:1.8.0_232]
        at sun.security.krb5.internal.crypto.Aes128CtsHmacSha1EType.decrypt(Aes128CtsHmacSha1EType.java:94) ~[?:1.8.0_232]
        at sun.security.krb5.EncryptedData.decrypt(EncryptedData.java:175) ~[?:1.8.0_232]
        at sun.security.krb5.KrbApReq.authenticate(KrbApReq.java:281) ~[?:1.8.0_232]
        at sun.security.krb5.KrbApReq.<init>(KrbApReq.java:149) ~[?:1.8.0_232]
        at sun.security.jgss.krb5.InitSecContextToken.<init>(InitSecContextToken.java:108) ~[?:1.8.0_232]
        at sun.security.jgss.krb5.Krb5Context.acceptSecContext(Krb5Context.java:831) ~[?:1.8.0_232]
        at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:342) ~[?:1.8.0_232]
        at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:285) ~[?:1.8.0_232]
        at com.sun.security.sasl.gsskerb.GssKrb5Server.evaluateResponse(GssKrb5Server.java:167) ~[?:1.8.0_232]
        ... 14 more

### How to reproduce

+ v0.6
Pls refer to the first part as discribed above

**Comment by tyoushinya** [comment]
@xxzhky  I tested this case seems every thing works well in my side. You can try change  gravitino.bypass.hive.metastore.kerberos.principal to hive/_HOST@DPOPSTEST.HADOOP
 BTW, hadoop common can replace the _HOST with actual hostname.

**Comment by mchades** [comment]
Feel free to open it if the provided answer above does not resolve the issue.
