### ISSUE TITLE
[Bug report] Sometimes build gravitino failed due to error: could not download node-21.6.1-linux-x64.tar.gz (org.nodejs:node:21.6.1)

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#5282]
### Version

main branch

### Describe what's wrong

In CI action, build gravitino failed.
./gradlew compileDistribution -x test -PjdkVersion=17 

### Error message and/or stacktrace

```
Build gravitino FAILURE reason:                                
    Caused by: org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':docs:nodeSetup'.
        Caused by: org.gradle.api.internal.provider.AbstractProperty$PropertyQueryException: Failed to query the value of task ':docs:nodeSetup' property 'nodeArchiveFile'.
            at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:145)
            at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:136)
            at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:98)
            at org.gradle.api.internal.provider.ProviderResolutionStrategy$1.resolve(ProviderResolutionStrategy.java:27)
            at org.gradle.api.internal.file.collections.ProviderBackedFileCollection.visitDependencies(ProviderBackedFileCollection.java:57)
                    at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$0(DefaultBuildOperationQueue.java:238)
                    at org.gradle.internal.resources.AbstractResourceLockRegistry.whileDisallowingLockChanges(AbstractResourceLockRegistry.java:50)
                    at org.gradle.internal.work.DefaultWorkerLeaseService.whileDisallowingProjectLockChanges(DefaultWorkerLeaseService.java:221)
                    at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$1(DefaultBuildOperationQueue.java:238)
                    at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
                    at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
                    at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:224)
                    at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:192)
                    ... 2 more
                    Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://nodejs.org/dist/v21.6.1/node-v21.6.1-linux-x64.tar.gz'.
                        at org.gradle.internal.resource.ResourceExceptions.failure(ResourceExceptions.java:74)
                        at org.gradle.internal.resource.ResourceExceptions.getFailed(ResourceExceptions.java:57)
                        at org.gradle.internal.resource.transfer.AbstractExternalResourceAccessor.withContent(AbstractExternalResourceAccessor.java:41)
                        at org.gradle.internal.resource.transfer.DefaultExternalResourceConnector.withContent(DefaultExternalResourceConnector.java:59)
                        at org.gradle.internal.resource.transfer.ProgressLoggingExternalResourceAccessor$DownloadOperation.call(ProgressLoggingExternalResourceAccessor.java:123)
                        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
                        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
                        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
                        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
                        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
                        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
                        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
                        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
                        at org.gradle.internal.resource.transfer.ProgressLoggingExternalResourceAccessor.withContent(ProgressLoggingExternalResourceAccessor.java:46)
                        at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.withContentIfPresent(AccessorBackedExternalResource.java:103)
                        at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.copyToCache(DefaultCacheAwareExternalResourceAccessor.java:188)
                        at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.lambda$getResource$1(DefaultCacheAwareExternalResourceAccessor.java:86)
                        at org.gradle.cache.internal.ProducerGuard$AdaptiveProducerGuard.guardByKey(ProducerGuard.java:97)
                        at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.getResource(DefaultCacheAwareExternalResourceAccessor.java:80)
                        at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadByCoords(DefaultExternalResourceArtifactResolver.java:149)
                        at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadStaticResource(DefaultExternalResourceArtifactResolver.java:[94](https://github.com/datastrato/gravitino-test/actions/runs/11543057054/job/32127011598#step:10:95))
                        at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.resolveArtifact(DefaultExternalResourceArtifactResolver.java:62)
                        at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver$RemoteRepositoryAccess.resolveArtifact(ExternalResourceResolver.java:464)
                        ... 32 more
                        Caused by: java.net.SocketTimeoutException: Read timed out
                            at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
                            at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:1[97](https://github.com/datastrato/gravitino-test/actions/runs/11543057054/job/32127011598#step:10:98))
                            at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
                            at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
                            at org.gradle.internal.resource.transfer.AbstractProgressLoggingHandler$ProgressLoggingInputStream.read(AbstractProgressLoggingHandler.java:63)
                            at com.google.common.io.CountingInputStream.read(CountingInputStream.java:64)
                            at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1309)
                            at org.apache.commons.io.IOUtils.copy(IOUtils.java:978)
                            at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1282)
                            at org.gradle.internal.resource.transfer.DownloadAction.execute(DownloadAction.java:59)
                            at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.lambda$withContentIfPresent$2(AccessorBackedExternalResource.java:105)
                            at org.gradle.internal.resource.transfer.ProgressLoggingExternalResourceAccessor$DownloadOperation.lambda$call$0(ProgressLoggingExternalResourceAccessor.java:130)
                            at org.gradle.internal.resource.transfer.AbstractExternalResourceAccessor.withContent(AbstractExternalResourceAccessor.java:39)
                            ... 52 more

   > Could not resolve all files for configuration ':docs:detachedConfiguration1'.
      > Could not download node-21.6.1-linux-x64.tar.gz (org.nodejs:node:21.6.1)
         > Could not get resource 'https://nodejs.org/dist/v21.6.1/node-v21.6.1-linux-x64.tar.gz'.
            > Read timed out

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5m 59s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
Error: Process completed with exit code 1.
```

### How to reproduce

It can be reproduced by CI

**Comment by danhuawang** [comment]
@yuqi1129 Can you help check this issue?

**Comment by jerryshao** [comment]
@mchades I assigned this issue to you, please sync with @LauraXia123 about this.

**Comment by mchades** [comment]
This is caused by a network issue and can be resolved by manually retrying. I will close this issue unless it becomes frequent.
