### ISSUE TITLE
[Bug report] Trino: postgres catalog: INSERT INTO TIMESTAMP WITH TIME ZONE datatype failed 

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#5341]
### Version

main branch

### Describe what's wrong

<img width="1849" alt="image" src="https://github.com/user-attachments/assets/38ea1851-d0de-446e-9fee-ac8a74548ebf">

### Error message and/or stacktrace

```
2024-10-29T09:57:45.070Z        INFO    dispatcher-query-62     io.trino.event.QueryMonitor     TIMELINE: Query 20241029_095745_01026_swkfi :: FINISHED :: elapsed 20ms :: planning 0ms :: waiting 0ms :: scheduling 20ms :: running 0ms :: finishing 20ms :: begin 2024-10-29T09:57:45.050Z :: end 2024-10-29T09:57:45.070Z
2024-10-29T09:58:08.303Z        ERROR   remote-task-callback-82 io.trino.execution.scheduler.PipelinedStageExecution    Pipelined stage execution for stage 20241029_095808_01027_swkfi.1 failed
java.lang.ClassCastException: class io.trino.spi.block.LongArrayBlock cannot be cast to class io.trino.spi.block.Fixed12Block (io.trino.spi.block.LongArrayBlock and io.trino.spi.block.Fixed12Block are in unnamed module of loader 'app')
        at io.trino.spi.type.LongTimestampWithTimeZoneType.getObject(LongTimestampWithTimeZoneType.java:130)
        at io.trino.plugin.jdbc.JdbcPageSink.appendColumn(JdbcPageSink.java:193)
        at io.trino.plugin.jdbc.JdbcPageSink.appendPage(JdbcPageSink.java:146)
        at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:278)
        at io.trino.operator.Driver.processInternal(Driver.java:403)
        at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
        at io.trino.operator.Driver.tryWithLock(Driver.java:704)
        at io.trino.operator.Driver.process(Driver.java:293)
        at io.trino.operator.Driver.processForDuration(Driver.java:264)
        at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
        at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
        at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
        at io.trino.$gen.Trino_435____20241029_022459_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)



```

### How to reproduce

1. create pg catalog
2. create pg schema
3.  create pg table in Trino 
```
CREATE TABLE pg0 (
    id INT,
    event_time TIMESTAMP WITH TIME ZONE
);

```
4. insert data into pg table
```
INSERT INTO pg0 (id, event_time) VALUES (2, TIMESTAMP '2024-10-29 15:00:00 UTC');
```

**Comment by danhuawang** [comment]
@diqiu50 Can you help check this issue?

**Comment by diqiu50** [comment]
That's a default time precision problem
