### ISSUE TITLE
[Bug report] Gravitino sever starting error and all apis reponse nothing

### ISSUE THREAD

**Issue by yujiantao** [apache/gravitino#5686]
### Version

main branch

### Describe what's wrong

version: 0.7.0-incubating

WEB-INF/lib/FastInfoset-1.2.15.jar is not found when gravitino server starts, and api responses nothing after  server is started.

### Error message and/or stacktrace

2024-11-27 10:04:58.341 WARN [main] [org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:533)] - Failed startup of context o.e.j.w.WebAppContext@1bc425e7{/,jar:file:///usr/local/service/tc-catalog/web/gravitino-web-0.7.0-incubating.war!/,STOPPED}{/usr/local/service/tc-catalog/web/gravitino-web-0.7.0-incubating.war}
java.io.FileNotFoundException: JAR entry WEB-INF/lib/FastInfoset-1.2.15.jar!/ not found in /usr/local/service/tc-catalog/web/gravitino-web-0.7.0-incubating.war
        at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:146) ~[?:?]
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:92) ~[?:?]
        at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:445) ~[jetty-webapp-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:361) ~[jetty-webapp-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:172) ~[jetty-webapp-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:106) ~[jetty-webapp-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488) ~[jetty-webapp-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523) [jetty-webapp-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.Server.start(Server.java:423) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.Server.doStart(Server.java:387) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.apache.gravitino.server.web.JettyServer.start(JettyServer.java:183) [gravitino-server-common-0.7.0-incubating.jar:?]
        at org.apache.gravitino.server.GravitinoServer.start(GravitinoServer.java:148) [gravitino-server-0.7.0-incubating.jar:?]
        at org.apache.gravitino.server.GravitinoServer.main(GravitinoServer.java:169) [gravitino-server-0.7.0-incubating.jar:?]
2024-11-27 10:04:58.423 INFO [main] [org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:333)] - Started ServerConnector@73ba6fe6{HTTP/1.1, (http/1.1)}{0.0.0.0:8090}

### How to reproduce

./bin/gravitino.sh --config $GRAVITINO_HOME/conf start

curl -L -X GET 'http://localhost:8090/api/version' -H 'Accept: application/vnd.gravitino.v1+json'

**Comment by yujiantao** [comment]
When I set shouldEnableUI = false, the problem disappeared

**Comment by orenccl** [comment]
It can be closed because it has been pending for a month with no response and no reproduction method provided.
