### ISSUE TITLE
[Bug report] http client out of time

### ISSUE THREAD

**Issue by an-shi-chi-fan** [apache/gravitino#5765]
### Version

main branch

### Describe what's wrong

I deployed a set of gravtino-0.7.0 and used my own frontend service to interface with gravtino's HTTP request client. When I manually click on the interface for a table or schema with slightly more data 50-60 times in a row, I frequently encounter timeout issues. Upon checking gravtino, I found many "Dead lock detected" logs, with many locks being held for over 30 seconds. What could be the possible reasons for this?

### Error message and/or stacktrace

just dead lock detected log，so i don't know what happend

### How to reproduce

0.7.0

**Comment by mchades** [comment]
> When I manually click on the interface for a table or schema with slightly more data 50-60 times in a row

Could you please explain which API you are specifically calling?

**Comment by mchades** [comment]
> Is it caused by the low concurrency of Gravitino

It should not be, since the list only requires a read lock.

Could you please provide more detailed instructions for reproduction? For instance, which specific catalog do you utilize and what magnitude of tables (schemas) do you include in your listings?

**Comment by an-shi-chi-fan** [comment]
> > Is it caused by the low concurrency of Gravitino
> 
> It should not be, since the list only requires a read lock.
> 
> Could you please provide more detailed instructions for reproduction? For instance, which specific catalog do you utilize and what magnitude of tables (schemas) do you include in your listings?

catalog is 24，the max catalog has 333 schemas， the max schema has 100 tables。

**Comment by mchades** [comment]
You can try increasing the value of the catalog property `client.pool-size`, which has a default value of 1.

**Comment by FANNG1** [comment]
`jstack` may provides some help to check which operation is obtaining the lock.  BYW @mchades  the default value of `client.pool-size` seems too small, is it expected?

**Comment by an-shi-chi-fan** [comment]
``` java
2024-12-06 17:14:12.297 ERROR [Gravitino-webserver-18] [org.apache.gravitino.server.web.rest.ExceptionHandlers$BaseExceptionHandler.handle(ExceptionHandlers.java:713)] - Failed to operate object operation [LIST] under [xxxx], reason [Failed to list all tables under the namespace : default.xxx.xxx in Hive Metastore]
java.lang.RuntimeException: Failed to list all tables under the namespace : default.xxx.xxx in Hive Metastore
	at org.apache.gravitino.catalog.hive.HiveCatalogOperations.listTables(HiveCatalogOperations.java:577) ~[?:?]
	at org.apache.gravitino.catalog.TableOperationDispatcher.lambda$listTables$0(TableOperationDispatcher.java:96) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithTableOps$1(CatalogManager.java:151) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:86) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.catalog.CatalogManager$CatalogWrapper.doWithTableOps(CatalogManager.java:146) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.catalog.TableOperationDispatcher.lambda$listTables$1(TableOperationDispatcher.java:96) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.catalog.OperationDispatcher.doWithCatalog(OperationDispatcher.java:100) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.catalog.TableOperationDispatcher.listTables(TableOperationDispatcher.java:94) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.hook.TableHookDispatcher.listTables(TableHookDispatcher.java:57) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.catalog.TableNormalizeDispatcher.listTables(TableNormalizeDispatcher.java:55) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.listener.TableEventDispatcher.listTables(TableEventDispatcher.java:77) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.server.web.rest.TableOperations.lambda$listTables$0(TableOperations.java:93) ~[gravitino-server-0.7.0-incubating.jar:?]
	at org.apache.gravitino.lock.TreeLockUtils.doWithTreeLock(TreeLockUtils.java:49) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.server.web.rest.TableOperations.lambda$listTables$1(TableOperations.java:90) ~[gravitino-server-0.7.0-incubating.jar:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	at java.base/javax.security.auth.Subject.doAs(Subject.java:439) ~[?:?]
	at org.apache.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:39) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.server.web.Utils.doAs(Utils.java:188) ~[gravitino-server-0.7.0-incubating.jar:?]
	at org.apache.gravitino.server.web.rest.TableOperations.listTables(TableOperations.java:84) ~[gravitino-server-0.7.0-incubating.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.apache.gravitino.server.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:86) ~[gravitino-server-common-0.7.0-incubating.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.apache.gravitino.server.web.VersioningFilter.doFilter(VersioningFilter.java:123) ~[gravitino-server-0.7.0-incubating.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: Got exception: org.apache.thrift.TApplicationException Internal error processing get_all_tables
	at org.apache.hadoop.hive.metastore.MetaStoreUtils.logAndThrowMetaException(MetaStoreUtils.java:1423) ~[?:?]
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getAllTables(HiveMetaStoreClient.java:1446) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:169) ~[?:?]
	at jdk.proxy3/jdk.proxy3.$Proxy102.getAllTables(Unknown Source) ~[?:?]
	at org.apache.gravitino.catalog.hive.HiveCatalogOperations.lambda$listTables$10(HiveCatalogOperations.java:544) ~[?:?]
	at org.apache.gravitino.utils.ClientPoolImpl.run(ClientPoolImpl.java:61) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.utils.ClientPoolImpl.run(ClientPoolImpl.java:52) ~[gravitino-core-0.7.0-incubating.jar:?]
	at org.apache.gravitino.hive.CachedClientPool.run(CachedClientPool.java:98) ~[?:?]
	at org.apache.gravitino.catalog.hive.HiveCatalogOperations.listTables(HiveCatalogOperations.java:544) ~[?:?]
	... 77 more

```

today i find the err stack is this.   @mchades

**Comment by an-shi-chi-fan** [comment]
> which

i  had used  jstack yesterday but not find dead lock log.

**Comment by an-shi-chi-fan** [comment]
> ```java
> 2024-12-06 17:14:12.297 ERROR [Gravitino-webserver-18] [org.apache.gravitino.server.web.rest.ExceptionHandlers$BaseExceptionHandler.handle(ExceptionHandlers.java:713)] - Failed to operate object operation [LIST] under [xxxx], reason [Failed to list all tables under the namespace : default.xxx.xxx in Hive Metastore]
> java.lang.RuntimeException: Failed to list all tables under the namespace : default.xxx.xxx in Hive Metastore
> 	at org.apache.gravitino.catalog.hive.HiveCatalogOperations.listTables(HiveCatalogOperations.java:577) ~[?:?]
> 	at org.apache.gravitino.catalog.TableOperationDispatcher.lambda$listTables$0(TableOperationDispatcher.java:96) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithTableOps$1(CatalogManager.java:151) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:86) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.catalog.CatalogManager$CatalogWrapper.doWithTableOps(CatalogManager.java:146) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.catalog.TableOperationDispatcher.lambda$listTables$1(TableOperationDispatcher.java:96) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.catalog.OperationDispatcher.doWithCatalog(OperationDispatcher.java:100) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.catalog.TableOperationDispatcher.listTables(TableOperationDispatcher.java:94) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.hook.TableHookDispatcher.listTables(TableHookDispatcher.java:57) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.catalog.TableNormalizeDispatcher.listTables(TableNormalizeDispatcher.java:55) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.listener.TableEventDispatcher.listTables(TableEventDispatcher.java:77) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.server.web.rest.TableOperations.lambda$listTables$0(TableOperations.java:93) ~[gravitino-server-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.lock.TreeLockUtils.doWithTreeLock(TreeLockUtils.java:49) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.server.web.rest.TableOperations.lambda$listTables$1(TableOperations.java:90) ~[gravitino-server-0.7.0-incubating.jar:?]
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
> 	at java.base/javax.security.auth.Subject.doAs(Subject.java:439) ~[?:?]
> 	at org.apache.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:39) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.server.web.Utils.doAs(Utils.java:188) ~[gravitino-server-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.server.web.rest.TableOperations.listTables(TableOperations.java:84) ~[gravitino-server-0.7.0-incubating.jar:?]
> 	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
> 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.41.jar:?]
> 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146) ~[jersey-server-2.41.jar:?]
> 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189) ~[jersey-server-2.41.jar:?]
> 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[jersey-server-2.41.jar:?]
> 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93) ~[jersey-server-2.41.jar:?]
> 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[jersey-server-2.41.jar:?]
> 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[jersey-server-2.41.jar:?]
> 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-2.41.jar:?]
> 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256) ~[jersey-server-2.41.jar:?]
> 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.41.jar:?]
> 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.41.jar:?]
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.41.jar:?]
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.41.jar:?]
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.41.jar:?]
> 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.41.jar:?]
> 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235) ~[jersey-server-2.41.jar:?]
> 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[jersey-server-2.41.jar:?]
> 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.41.jar:?]
> 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.41.jar:?]
> 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) ~[jersey-container-servlet-core-2.41.jar:?]
> 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) ~[jersey-container-servlet-core-2.41.jar:?]
> 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.41.jar:?]
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.apache.gravitino.server.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:86) ~[gravitino-server-common-0.7.0-incubating.jar:?]
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.apache.gravitino.server.web.VersioningFilter.doFilter(VersioningFilter.java:123) ~[gravitino-server-0.7.0-incubating.jar:?]
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
> 	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: org.apache.hadoop.hive.metastore.api.MetaException: Got exception: org.apache.thrift.TApplicationException Internal error processing get_all_tables
> 	at org.apache.hadoop.hive.metastore.MetaStoreUtils.logAndThrowMetaException(MetaStoreUtils.java:1423) ~[?:?]
> 	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getAllTables(HiveMetaStoreClient.java:1446) ~[?:?]
> 	at jdk.internal.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:169) ~[?:?]
> 	at jdk.proxy3/jdk.proxy3.$Proxy102.getAllTables(Unknown Source) ~[?:?]
> 	at org.apache.gravitino.catalog.hive.HiveCatalogOperations.lambda$listTables$10(HiveCatalogOperations.java:544) ~[?:?]
> 	at org.apache.gravitino.utils.ClientPoolImpl.run(ClientPoolImpl.java:61) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.utils.ClientPoolImpl.run(ClientPoolImpl.java:52) ~[gravitino-core-0.7.0-incubating.jar:?]
> 	at org.apache.gravitino.hive.CachedClientPool.run(CachedClientPool.java:98) ~[?:?]
> 	at org.apache.gravitino.catalog.hive.HiveCatalogOperations.listTables(HiveCatalogOperations.java:544) ~[?:?]
> 	... 77 more
> ```
> 
> today i find the err stack is this. @mchades

in my hive metastore service. i find this error stack

```java
2024-12-06 17:12:24.350 ERROR [HiveServer2-Handler-Pool: Thread-1752|1752] server.TThreadPoolServer: Error occurred during processing of message.
java.lang.RuntimeException: org.apache.thrift.transport.TSaslTransportException: No data or no sasl data in the stream
	at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:219) ~[hive-exec-3.1.3.jar:3.1.3]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269) ~[hive-exec-3.1.3.jar:3.1.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_322]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
Caused by: org.apache.thrift.transport.TSaslTransportException: No data or no sasl data in the stream
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:328) ~[hive-exec-3.1.3.jar:3.1.3]
	at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) ~[hive-exec-3.1.3.jar:3.1.3]
	at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) ~[hive-exec-3.1.3.jar:3.1.3]
	... 4 more

```

**Comment by mchades** [comment]
Are there any error logs in HMS?

**Comment by mchades** [comment]
> java.lang.RuntimeException: Failed to list all tables under the namespace : default.xxx.xxx in Hive Metastore

According to the log, I guess the problem may lie in HMS.

**Comment by an-shi-chi-fan** [comment]
> may

yes, it is.   i found error log in hms

**Comment by an-shi-chi-fan** [comment]
thanks @mchades @FANNG1

**Comment by an-shi-chi-fan** [comment]
hive metastore service time out
