### ISSUE TITLE
[Improvement] When a malformed name is passed to the CLI command to list columns in a table an exception occurs

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5808]
### What would you like to be improved?

When running this:
`gcli table  list -i --metalake metalake_demo --name catalog_postgres`

This is the output:
```
Malformed entity name.
Exception in thread "main" org.apache.gravitino.exceptions.IllegalNamespaceException: Cannot create a namespace with null or empty level
	at org.apache.gravitino.Namespace.check(Namespace.java:151)
	at org.apache.gravitino.Namespace.of(Namespace.java:61)
	at org.apache.gravitino.cli.commands.ListTables.handle(ListTables.java:52)
	at org.apache.gravitino.cli.GravitinoCommandLine.handleTableCommand(GravitinoCommandLine.java:316)
	at org.apache.gravitino.cli.GravitinoCommandLine.executeCommand(GravitinoCommandLine.java:130)
	at org.apache.gravitino.cli.GravitinoCommandLine.handleCommandLine(GravitinoCommandLine.java:92)
	at org.apache.gravitino.cli.Main.main(Main.java:47)
```

### How should we improve?

No exception should occur. Note this doesn't occur with other list commands.

**Comment by Abyss-lord** [comment]
Hi Justin, Could you please assign this issue to me? I would like to work on it.

**Comment by justinmclean** [comment]
Done. Feel free to add a comment saying you are working on an issue without me assigning it to you. I can assign it to you after you have started working on it.
