### ISSUE TITLE
[Improvement] Update the version of hadoop gcs connector in module `gcp-bundle`

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#5971]
### What would you like to be improved?

The version of gcs-connector used in moudle `gcp-bundle` is `1.9.4-hadoop3`, which is quite out of date, we need to update it to support access token.

**Comment by yuqi1129** [comment]
This is no needed any more.

**Comment by yuqi1129** [comment]
Reopen it as module `authorization-gcp-iam` relys on a higher version of GCS, we need to update it or error like 

```
Caused by: java.lang.NoSuchMethodError: com.google.api.services.storage.Storage$Buckets$GetIamPolicy.setOptionsRequestedPolicyVersion(Ljava/lang/Integer;)Lcom/google/api/services/storage/Storage$Buckets$GetIamPolicy;
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.getIamPolicy(HttpStorageRpc.java:1663) ~[?:?]
	at com.google.cloud.storage.StorageImpl.lambda$getIamPolicy$52(StorageImpl.java:1548) ~[?:?]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:102) ~[?:?]
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[?:?]
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[?:?]
	at com.google.cloud.storage.Retrying.run(Retrying.java:65) ~[?:?]
	at com.google.cloud.storage.StorageImpl.run(StorageImpl.java:1608) ~[?:?]
	at com.google.cloud.storage.StorageImpl.getIamPolicy(StorageImpl.java:1546) ~[?:?]
	at org.apache.gravitino.authorization.gcp.iam.GCPIAMAuthorizationPlugin.addUserOrGroupToRole(GCPIAMAuthorizationPlugin.java:818) ~[?:?]
	at org.apache.gravitino.authorization.gcp.iam.GCPIAMAuthorizationPlugin.lambda$grantSecurableObjectToUserOrGroup$9(GCPIAMAuthorizationPlugin.java:942) ~[?:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.3-jre.jar:?]
	at org.apache.gravitino.authorization.gcp.iam.GCPIAMAuthorizationPlugin.grantSecurableObjectToUserOrGroup(GCPIAMAuthorizationPlugin.java:935) ~[?:?]
	at org.apache.gravitino.authorization.gcp.iam.GCPIAMAuthorizationPlugin.onOwnerSet(GCPIAMAuthorizationPlugin.java:1184) ~[?:?]
	at org.apache.gravitino.authorization.OwnerManager.lambda$setOwner$2(OwnerManager.java:115) ~[gravitino-core-0.9.0-incubating-SNAPSHOT.jar:?]
	at org.apache.gravitino.authorization.AuthorizationUtils.callAuthorizationPluginImpl(AuthorizationUtils.java:369) ~[gravitino-core-0.9.0-incubating-SNAPSHOT.jar:?]
	at org.apache.gravitino.authorization.AuthorizationUtils.callAuthorizationPluginForMetadataObject(AuthorizationUtils.java:194) ~[gravitino-core-0.9.0-incubating-SNAPSHOT.jar:?]
	at org.apache.gravitino.authorization.OwnerManager.setOwner(OwnerManager.java:111) ~[gravitino-core-0.9.0-incubating-SNAPSHOT.jar:?]
	at org.apache.gravitino.hook.CatalogHookDispatcher.createCatalog(CatalogHookDispatcher.java:88) ~[gravitino-core-0.9.0-incubating-SNAPSHOT.jar:?]
	at org.apache.gravitino.catalog.CatalogNormalizeDispatcher.createCatalog(CatalogNormalizeDispatcher.java:88) ~[gravitino-core-0.9.0-incubating-SNAPSHOT.jar:?]
	at org.apache.gravitino.listener.CatalogEventDispatcher.createCatalog(CatalogEventDispatcher.java:131) ~[gravitino-core-0.9.0-incubating-SNAPSHOT.jar:?]
	at org.apache.gravitino.server.web.rest.CatalogOperations.lambda$createCatalog$2(CatalogOperations.java:137) ~[gravitino-server-0.9.0-incubating-SNAPSHOT.jar:?]
	at org.apache.gravitino.lock.TreeLockUtils.doWithTreeLock(TreeLockUtils.java:49) ~[gravitino-core-0.9.0-incubating-SNAPSHOT.jar:?]
	at org.apache.gravitino.server.web.rest.CatalogOperations.lambda$createCatalog$3(CatalogOperations.java:133) ~[gravitino-server-0.9.0-incubating-SNAPSHOT.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_372]
```
